@startuml
title ROSCAN Workspace Components
package ROSCAN <<workspace>>{
component "roscan_pkg" as roscan
component "canplay_pkg" as canplay
component "gps_service_pkg" as gps
component "can_interfaces" as interfaces
note top
	Registrarion Service Message
	And CAN Message Definitions
endnote
package "external includes" as includes{
	component CANFactory
	component CommonCore
	component GpsService
	note bottom
		CAN Message Definitions
		And Bridge Struct Definitions
	endnote
	component JDMath
	component JDProjection
}
}
component ApplicationNode
artifact CANLogFile.txt as log

log-->canplay
canplay-->roscan : CAN MSGS\nmessage_queue\n <<boost>>
canplay<-->roscan : RegisterMsg\n <<ros2>>
roscan-->gps : Bridged CAN Messages\n <<ros2>>
gps-->ApplicationNode : GPS Epoch Messages\n <<ros2>>

@enduml