uint8 RV_GEN2 = 0
uint8 RV_GEN4 = 1
uint8 RV_LOW_COST = 2
uint8 RV_GEN5 = 3
uint8 RV_GEN6 = 4
uint8 RV_SF7000 = 5
uint8 RV_RESERVED2 = 6
uint8 RV_RESERVED3 = 7
uint8 RV_RESERVED4 = 8
uint8 RV_RESERVED5 = 9
uint8 RV_RESERVED6 = 10
uint8 RV_RESERVED7 = 11
uint8 RV_RESERVED8 = 12
uint8 RV_RESERVED9 = 13
uint8 RV_ERROR = 14
uint8 RV_NOT_AVAILABLE = 15

uint16 license_days
uint8 hardware_version
uint8 software_version
uint32 serial_number
uint8 receiver_version
